language: python

python:
  - 2.7
env:
  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.
  ## Out of tree builds (default):
  # Debug build
  - BUILD_TYPE="Debug"
  
  #reset_minion: true

matrix:
  include:
    # These test the default Release build with other Python versions
    - python: 3.3
      env:
        - WITH_PYTHON="yes"
   
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libgmp-dev
  - if [[ "${WITH_BFD}" == "yes" ]]; then
        sudo apt-get install binutils-dev;
    fi
  - if [[ "${WITH_ECM}" == "yes" ]]; then
        sudo apt-get install libecm-dev;
    fi
  - if [[ "${WITH_PRIMESIEVE}" == "yes" ]]; then
        wget http://dl.bintray.com/kimwalisch/primesieve/primesieve-5.2.tar.gz;
        tar -xzvf primesieve-5.2.tar.gz;
        cd primesieve-5.2 && ./configure && make && sudo make install && cd ..;
    fi
install:
  - if [[ "${WITH_PYTHON}" == "yes" ]]; then
        pip install cython sympy --use-mirrors;
    fi
script:
  - bin/test_travis.sh

archive: true

notifications:
     email:
         recipients:
             - vidya@shippable.com
             - buildsampletest@gmail.com
         on_success: always
         on_failure: always

#cache: true
